package com.mintdigital.cardscheme.domain.dto;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;


/**
 *	CardDetailsDTO generated by JCodeGenTool v1.2
 *  @author : Owolabi Babalola
 *  @email : babs.owolabi@gmail.com
 * 
 */

@Data
@Builder
@AllArgsConstructor
public class CardDetailsDto implements java.io.Serializable {

	private static final long serialVersionUID = -7555070770070055331L;
	/**
	 * The fields below are extracted
	 * from the CardDetails Entity
	 */
	private String id;
	private String cardNumber;
	private Character status;
	private Long numberOfHits;
	private String cardType;
	private String cardScheme;
	private String bankName;

	public CardDetailsDto() {
	}

	@Override
	public String toString() {
		return "CardDetailsDto{" +
				" id= " + id +
				", cardNumber= " + cardNumber +
				", status= " + status +
				", numberOfHits= " + numberOfHits +
				", cardScheme= " + cardScheme +
				", bankName= " + bankName +
				"}";


	}
}